income/urls.py
from django.urls import path
from .import views as v
urlpatterns = [
    path('add',v.add_income,name="add"),
    path('list',v.income_list,name="list"),
    path('delete/<int:id>',v.delete_income,name="delete"),
    path('serch-income-type/<str:data>',v.search_by_incometype,name="search_type"),
]

income/models.py
import imp
from django.db import models
from django.contrib.auth.models import User
class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    incom_date=models.DateField(auto_now=True)
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        db_table="income"

from django import forms

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

income/views.py
from datetime import date
from django.shortcuts import redirect, render
from .models import Income,IncomeForm,User

def add_income(request):
    if request.method=='POST':
        inc=Income()
        income=request.POST.get("income")
        income_type=request.POST.get("income_type")
         
        description=request.POST.get("description")
        inc.income=income
        
        inc.income_type=income_type
        inc.description=description
        uid=request.session.get("uid")
        usr=User.objects.get(id=uid)
        inc.user=usr
        inc.save()
        return redirect("/")
    else:
        f=IncomeForm
        context={'form':f}
        return render(request,'addincome.html',context)


def income_list(request):
  uid=request.session.get("uid")
  usr=User.objects.get(id=uid)
  incl=Income.objects.filter(user=usr)
  inctype=set()
  for i in incl:
    inctype.add(i.income_type)
  if request.method=='POST':
    srch=request.POST.get("search")
    inclist=Income.objects.filter(user=usr,description__contains=srch)
    return render(request,'incomelist.html',{'incl':inclist,'inctype':inctype})  
  else:
    return render(request,'incomelist.html',{'incl':incl,'inctype':inctype})  

def search_by_incometype(request,data):
  uid=request.session.get("uid")
  usr=User.objects.get(id=uid)
  incl=Income.objects.filter(user=usr)
  inctype=set()
  for i in incl:
    inctype.add(i.income_type)
  inclist=Income.objects.filter(user=usr,income_type=data)
  return render(request,"incomelist.html",{'incl':inclist,'inctype':inctype})

def delete_income(request,id):
  inc=Income.objects.get(id=id)
  inc.delete()
  return redirect("/")
  

income/templates/addincome.html
{%extends 'base.html'%}
{%block body%}
<form method="post">
    {%csrf_token%}
    <table cellspacing="10" border="1">
        <tr>
            <th><label for="id_income">Income:</label></th>
            <td><input type="number" name="income" required id="id_income"></td>
        </tr>
        <tr>
            <th><label for="id_income_type">Income type:</label></th>
            <td><input type="text" name="income_type" maxlength="30" required id="id_income_type"></td>
        </tr>
       
        <tr>
            <th><label for="id_description">Description:</label></th>
            <td><textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea></td>
        </tr>
        <tr>
            <th><label for="id_user">User:</label></th>
            <td><input type="text" name="user" value="{{user.username}}"></td>
        <tr>
            <td><input type="submit" value="Save"></td>
            <td><input type="submit" value="Reset"></td>
        </tr>

    </table>
</form>
{%endblock%}

income/templates/incomelist.html
{%extends 'base.html'%}
{%block body%}

<br>
<form method="post">
    {%csrf_token%}
    <textarea name="search"  cols="60" rows="3"></textarea> &nbsp;&nbsp;&nbsp;
    <input type="submit" value="Search">
</form>
<br>
<table border="1" cellspacing="10">
    <tr>
        <th>ID</th>
        <th>Income</th>
        <th>IncomeType</th>
        <th>IncomeDate</th>
        <th>Description</th>
        <th colspan="2">Action</th>
    </tr>

    {%for i in incl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.incom_date}}</td>
        <td>
            <textarea name="" id="" cols="20" rows="3">{{i.description}}</textarea>
        </td>

        <td><a href="{%url 'income:delete' i.id %}">Delete</a></td>
        <td><a href="">Edit</a></td>
    </tr>
    {%endfor%}

</table>

<style>
    #rside{
        width: 200px;
        height: 100%;
        background-color: aqua;
        position: fixed;
        right: 0%;
        top: 0%;
    }

    #rside   a{
        color: black;
        padding: 10px;
        margin: 10px;
    }
    
    #rside   a:hover{
        background-color: bisque;
    }
</style>

<div id="rside">
    <br>
    <h2> By IncomeType</h2>
    <ul>
    <li><h3><a href="{%url 'income:list'  %}">All</a></h3></li>
        {%for i in inctype%}
        <li><h3><a href="{%url 'income:search_type' i %}">{{i}}</a></h3></li>
        {%endfor%}
    </ul>
    <h2> By Amount Range </h2>
</div>

{%endblock%}